### ISSUE TITLE
即热模式不开启加热

### ISSUE THREAD

**Issue by sclsj** [banto6/haier#75]
**问题描述**

1. 从其他模式切换到即热后，不开始加热
2. 在即热模式下，开机后不开始加热
3. 到达目标温度（如75）后切换为保温模式，温度下降很多后（如60）再切换为加热模式【没有看到改变这个温度或者逻辑的选项】

**环境信息:**
 - Homeassistant版本: 2023.12.3
 - 运行环境：Docker 4.6.1 (76265)，m1 max macbook pro

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。（找不到，`cat /Users/jin/Downloads/error_log\ \(download\ full\ log\)2.txt | grep -i "Device Info"`没有输出）
```
deviceType:
productCodeT:
productNameT:
wifiType:
```
加载完整日志直接导致400%CPU，过十几秒标签页奔溃（错误代码5）。设备型号KF75/200-LE-U1。

**错误日志**
大概600MB，应该使用什么服务上传最方便？

**Comment by sclsj** [comment]
使用的automation：
```
alias: Shut off heater at 11:00PM
description: ""
trigger:
  - platform: time
    at: "23:00:00"
condition:
  - condition: device
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    domain: select
    entity_id: c9df665da592bd77f213c74979a4b655
    type: selected_option
    option: 即热模式
  - type: is_temperature
    condition: device
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    entity_id: 762e2c41218f16b0e2cff79cb1cbef39
    domain: sensor
    above: 40
action:
  - type: turn_off
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    entity_id: 076cf2636d86bca573e90fec9a1151fc
    domain: switch
mode: single
```
```
alias: Turn on heater at 1:30 AM
description: ""
trigger:
  - platform: time
    at: "01:30:00"
  - type: temperature
    platform: device
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    entity_id: 762e2c41218f16b0e2cff79cb1cbef39
    domain: sensor
    above: 10
    below: 40
condition:
  - condition: device
    type: is_off
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    entity_id: 076cf2636d86bca573e90fec9a1151fc
    domain: switch
  - condition: time
    after: "01:30:00"
action:
  - type: turn_on
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    entity_id: 076cf2636d86bca573e90fec9a1151fc
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: script.start_heating_now
    data: {}
mode: single
```
```
alias: Start heating when temperature drops below 75
description: ""
trigger:
  - type: temperature
    platform: device
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    entity_id: 762e2c41218f16b0e2cff79cb1cbef39
    domain: sensor
    above: 10
    below: 76
condition:
  - type: is_off
    condition: device
    device_id: b5f1778a6c03a511cb79cbcbcdf7bdd4
    entity_id: 240da84f653a5956c88f5d9a322a993d
    domain: binary_sensor
action:
  - service: script.start_heating_now
    data: {}
mode: single
```
